# These are supported funding model platforms

github: [carlosgamezvillegas] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
tidelift: npmjs.com/package/homebridge-oppo-udp  # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
custom:['https://paypal.me/carlosgamezv'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
